version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:641392857770:task-definition/netcore-dockerization:1"
        LoadBalancerInfo:
          ContainerName: "netcore-dockerization-containe"
          ContainerPort: "80"
        PlatformVersion: "LATEST"